stages:
  - build
  - test

build:
  stage: build
  image: docker-cppcheck
  script:
    - cd ARRgame/functions/
    - gcc -Wall -Werror -pedantic -c arrgame_functions_*.c
    - cppcheck --all arrgame_functions_*.c
  only:
    - branches
  except:
    - IMDBBot
    - MDBBot_dockerized
    - master
    - arrgame_ci
#test:
#  stage: test
#  image: gcc
#  script:
#    - cd ARRgame/tests/
#    - gcc -Wall -Werror -pedantic -o test *.c
#    - ./test
#  only:
#    - branches
#  except:
#    - IMDBBot
#    - MDBBot_dockerized
#    - master
#    - arrgame_ci
