stages:
  - build
  - test

build:
  stage: build
  image: gcc
  script:
    - cd ARRgame/functions/
    - apt-get update -y
    - apt-get install -y cppcheck
    - gcc -Wall -Werror -pedantic -c arrgame_functions_*.c
    - cppcheck --enable=all arrgame_functions_*.c
  only:
    - branches
  except:
    - IMDBBot
    - IMDBBot_dockerized
    - arrgame_dockerized
    - arrgame_map_filter_reduce
    - master

build-openmp:
  stage: build
  image: gcc
  script:
    - cd ARRgame/functions/
    - apt-get update -y
    - apt-get install -y cppcheck
    - gcc -Wall -Werror -pedantic -c -fopenmp arrgame_functions_*.c
    - cppcheck --enable=all arrgame_functions_*.c
  only:
    - arrgame_map_filter_reduce

test:
  stage: test
  image: gcc
  script:
    - cd ARRgame/tests/
    - apt-get update -y
    - apt-get install -y cppcheck
    - gcc -Wall -Werror -pedantic -o test arrgame_tests_*.c
    - cppcheck --enable=all arrgame_tests_*.c
    - ./test
  only:
    - branches
  except:
    - IMDBBot
<<<<<<< HEAD
    - MDBBot_dockerized
    - master
=======
    - IMDBBot_dockerized
    - arrgame_dockerized
    - arrgame_map_filter_reduce
    - master

test-openmp:
  stage: test
  image: gcc
  script:
    - cd ARRgame/tests/
    - apt-get update -y
    - apt-get install -y cppcheck
    - gcc -Wall -Werror -pedantic -c -fopenmp arrgame_tests_*.c
    - cppcheck --enable=all arrgame_tests_*.c
  only:
    - arrgame_map_filter_reduce
>>>>>>> arrgame_ci_openmp
