stages:
  - build
  - test

variables:
  TITANICGAME_FUNCS_PATH: TITANICgame/functions/
  TITANICGAME_FUNCS_TESTS_PATH: TITANICgame/f_tests/
  TITANICGAME_PLAYERS_PATH: TITANICgame/decision_trees/

build_titanicgame_func:
  stage: build
  image: gcc
  script:
    - apt update -y
    - gcc -Wall -Werror -c ${TITANICGAME_FUNCS_PATH}${CI_COMMIT_REF_NAME}.c
  after_script:
    - rm *.o
  only:
    refs:
      - /^.*_titanicgame$/
  except:
    refs:
      - /^.*_d6n_tree_titanicgame$/

build_titanicgame_strat:
  stage: build
  image: gcc
  script:
    - apt update -y
    - gcc -Wall -Werror -c ${TITANICGAME_PLAYERS_PATH}${CI_COMMIT_REF_NAME}.c
  after_script:
    - rm *.o
  only:
    refs:
      - /^.*_d6n_tree_titanicgame$/

test_titanicgame_func:
  stage: test
  image: gcc
  script:
    - apt update -y
    - apt install libperlio-gzip-perl libjson-perl -y
    - git clone https://github.com/linux-test-project/lcov
    - cd lcov/
    - make install
    - cd ..
    - export CUR_FUNC_TEST=$(echo "$CI_COMMIT_REF_NAME" | sed 's/_titanicgame/_test_titanicgame/')
    - gcc -Wall -Werror -c ${TITANICGAME_FUNCS_TESTS_PATH}${CUR_FUNC_TEST}.c
    - gcc -Wall -Werror -fprofile-arcs -ftest-coverage -c ${TITANICGAME_FUNCS_PATH}${CI_COMMIT_REF_NAME}.c
    - gcc -lgcov --coverage -o test.exe ${CUR_FUNC_TEST}.o ${CI_COMMIT_REF_NAME}.o
    - ./test.exe
    - lcov -t "test" -o test.info -c -d .
    - genhtml -o ${TITANICGAME_TESTS_PATH}${CI_COMMIT_REF_NAME}_codecoverage test.info
  after_script:
    - rm -rf lcov/
    - rm *.o *.gcda *.gcno *.exe
  artifacts:
    name: codecoverage
    paths:
      - ${TITANICGAME_TESTS_PATH}${CI_COMMIT_REF_NAME}_codecoverage
    when: on_success
  only:
    refs:
      - /^.*_titanicgame$/
  except:
    refs:
      - /^.*_d6n_tree_titanicgame$/

test_titanicgame_strat:
  stage: test
  image: gcc
  script:
    - apt update -y
    - sed -i 's/function_name/'${CI_COMMIT_REF_NAME}'/' ${TITANICGAME_FUNCS_PATH}survival_titanicgame.c
    - gcc -Wall -Werror -c ${TITANICGAME_PLAYERS_PATH}${CI_COMMIT_REF_NAME}.c
    - gcc -Wall -Werror -c ${TITANICGAME_FUNCS_PATH}survival_titanicgame.c
    - gcc -o run.exe *.o
    - ./run.exe > result.txt
    - echo YOUR PREDICTION RATE IS '\033[1;32m' $(cat result.txt) % '\033[0m'
  after_script:
    - rm *.o *.exe
  artifacts:
    name: kagglepurp
    paths:
      - TITANICgame/submission/submission.csv
    when: on_success
  only:
    refs:
      - /^.*_d6n_tree_titanicgame$/
