stages:
  - build
  - test

variables:
  MATRIX_FUNCS_PATH: MATRIXgame/functions/
  MATRIX_HEADERS_PATH: MATRIXgame/headers/
  MATRIX_TESTS_PATH: MATRIXgame/tests/

build_matrixgame:
  stage: build
  image: gcc
  script:
    - cd $MATRIX_FUNCS_PATH
    - gcc -Wall -Werror -c matrixgame_functions_*.c
  after_script:
    - cd $MATRIX_FUNCS_PATH
    - rm *.o
  only:
    refs:
      - /^matrixgame_.*$/
    changes:
      - ${MATRIX_FUNCS_PATH}*.{c}
      - ${MATRIX_HEADERS_PATH}*.{h}
      - ${MATRIX_TESTS_PATH}*.{c}
  except:
    refs:
      - matrixgame_transpose

build_matrixgame_openmp:
  stage: build
  image: gcc
  script:
    - cd $MATRIX_FUNCS_PATH
    - gcc -Wall -Werror -c -fopenmp matrixgame_functions_*.c
  after_script:
    - cd $MATRIX_FUNCS_PATH
    - rm *.o
  only:
    refs:
      - matrixgame_transpose
    changes:
      - ${MATRIX_FUNCS_PATH}*.c
      - ${MATRIX_HEADERS_PATH}*.h
      - ${MATRIX_TESTS_PATH}*.c

test_matrixgame:
  stage: test
  image: gcc
  before_script:
    - rm -rf ${MATRIX_TESTS_PATH}/${CI_COMMIT_REF_NAME}_codecoverage/
  script:
    - apt update -y
    - apt install libperlio-gzip-perl libjson-perl -y
    - git clone https://github.com/linux-test-project/lcov
    - cd lcov/
    - make install
    - cd ../$MATRIX_TESTS_PATH
    - gcc -Wall -Werror -fprofile-arcs -ftest-coverage -c matrixgame_tests_*.c
    - cd ../../$MATRIX_FUNCS_PATH
    - gcc -Wall -Werror -fprofile-arcs -ftest-coverage -c matrixgame_functions_*.c
    - gcc -lgcov --coverage -o test.exe ../../$MATRIX_TESTS_PATH/matrixgame_tests_*.o matrixgame_functions_*.o
    - ./test.exe
    - lcov -t "test" -o test.info -c -d .
    - genhtml -o ../tests/${CI_COMMIT_REF_NAME}_codecoverage test.info
    - git config user.name "$GITLAB_USER_NAME"
    - git config user.email $GITLAB_USER_EMAIL
    - git add ../tests/${CI_COMMIT_REF_NAME}_codecoverage/
    - git commit -m "Add codecoverage directory for $CI_COMMIT_REF_NAME function"
    - git push https://${DEPLOY_USER}:${DEPLOY_TOKEN}@git.iu7.bmstu.ru/aolenev/iu7-cprog-sems-2019-aolenev.git HEAD:$CI_COMMIT_REF_NAME
  after_script:
    - rm -rf lcov/
    - cd $MATRIX_FUNCS_PATH
    - rm *.o *.gcda *.gcno *.exe
    - cd ../../$MATRIX_TESTS_PATH
    - rm *.o *.gcda *.gcno
  only:
    refs:
      - /^matrixgame_.*$/
    changes:
      - ${MATRIX_FUNCS_PATH}*.c
      - ${MATRIX_HEADERS_PATH}*.h
      - ${MATRIX_TESTS_PATH}*.c
  except:
    refs:
      - matrixgame_transpose

test_matrixgame_openmp:
  stage: test
  image: gcc
  before_script:
    - rm -rf $MATRIX_TESTS_PATH/${CI_COMMIT_REF_NAME}_codecoverage/
  script:
    - apt update -y
    - apt install libperlio-gzip-perl libjson-perl -y
    - git clone https://github.com/linux-test-project/lcov
    - cd lcov/
    - make install
    - cd ../$MATRIX_TESTS_PATH
    - gcc -Wall -Werror -fopenmp -fprofile-arcs -ftest-coverage -c matrixgame_tests_*.c
    - cd ../../$MATRIX_FUNCS_PATH
    - gcc -Wall -Werror -fopenmp -fprofile-arcs -ftest-coverage -c matrixgame_functions_*.c
    - gcc -lgcov --coverage -fopenmp -o test.exe ../../$MATRIX_TESTS_PATH/matrixgame_tests_*.o matrixgame_functions_*.o
    - ./test.exe
    - lcov -t "test" -o test.info -c -d .
    - genhtml -o ../tests/${CI_COMMIT_REF_NAME}_codecoverage test.info
    - git config user.name "$GITLAB_USER_NAME"
    - git config user.email $GITLAB_USER_EMAIL
    - git add ../tests/${CI_COMMIT_REF_NAME}_codecoverage/
    - git commit -m "Add codecoverage directory for $CI_COMMIT_REF_NAME function"
    - git push https://${DEPLOY_USER}:${DEPLOY_TOKEN}@git.iu7.bmstu.ru/aolenev/iu7-cprog-sems-2019-aolenev.git HEAD:$CI_COMMIT_REF_NAME
  after_script:
    - rm -rf lcov/
    - cd $MATRIX_FUNCS_PATH
    - rm *.o *.gcda *.gcno *.exe
    - cd ../../$MATRIX_TESTS_PATH
    - rm *.o *.gcda *.gcno
  only:
    refs:
      - matrixgame_transpose
    changes:
      - ${MATRIX_FUNCS_PATH}*.c
      - ${MATRIX_HEADERS_PATH}*.h
      - ${MATRIX_TESTS_PATH}*.c
