stages:
  - build
  - test

variables:
  TEEN48GAME_FUNCS_PATH: TEEN48game/functions/
  TEEN48GAME_FUNCS_TESTS_PATH: TEEN48game/f_tests/
  TEEN48GAME_PLAYERS_PATH: TEEN48game/players
  TEEN48GAME_PLAYERS_TESTS_PATH: TEEN48game/p_tests

build_teen48game_func:
  stage: build
  image: gcc
  script:
    - apt update -y
    - wget http://catfella.space/pkg/matrixgame_1_0-1_amd64.deb
    - dpkg -i matrixgame_1_0-1_amd64.deb
    - gcc -Wall -Werror -c ${TEEN48GAME_FUNCS_PATH}${CI_COMMIT_REF_NAME}.c -larrgame -lmatrixgame
  after_script:
    - rm *.o
  only:
    refs:
      - /^teen48game_.*$/
  except:
    refs:
      - /^teen48game_player_.*$/
      - teen48game_ci

build_teen48game_strat:
  stage: build
  image: gcc
  script:
    - apt update -y
    - wget http://catfella.space/pkg/matrixgame_1_0-1_amd64.deb
    - dpkg -i matrixgame_1_0-1_amd64.deb
    - gcc -Wall -Werror -c ${TEEN48GAME_PLAYERS_PATH}${CI_COMMIT_REF_NAME}.c -larrgame -lmatrixgame
  after_script:
    - rm *.o
  only:
    refs:
      - /^teen48game_player_.*$/

test_teen48game_func:
  stage: test
  image: gcc
  script:
    - apt update -y
    - apt install libperlio-gzip-perl libjson-perl -y
    - wget http://catfella.space/pkg/matrixgame_1_0-1_amd64.deb
    - dpkg -i matrixgame_1_0-1_amd64.deb
    - git clone https://github.com/linux-test-project/lcov
    - cd lcov/
    - make install
    - cd ..
    - gcc -Wall -Werror -c ${TEEN48GAME_FUNCS_TESTS_PATH}${CI_COMMIT_REF_NAME}_tests.c -larrgame -lmatrixgame
    - gcc -Wall -Werror -fprofile-arcs -ftest-coverage -c ${TEEN48GAME_FUNCS_PATH}${CI_COMMIT_REF_NAME}.c -larrgame -lmatrixgame
    - gcc -lgcov --coverage -o test.exe ${CI_COMMIT_REF_NAME}_tests.o ${CI_COMMIT_REF_NAME}.o -larrgame -lmatrixgame
    - ./test.exe
    - lcov -t "test" -o test.info -c -d .
    - genhtml -o ${TEEN48GAME_TESTS_PATH}${CI_COMMIT_REF_NAME}_codecoverage test.info
  after_script:
    - rm -rf lcov/
    - rm *.o *.gcda *.gcno *.exe
  artifacts:
    name: codecoverage
    paths:
      - ${TEEN48GAME_TESTS_PATH}${CI_COMMIT_REF_NAME}_codecoverage
    when: on_success
  only:
    refs:
      - /^teen48game_.*$/
  except:
    refs:
      - /^teen48game_player_.*$/
      - teen48game_ci

test_teen48game_strat:
  stage: test
  image: gcc
  script:
    - apt update -y
    - apt install libperlio-gzip-perl libjson-perl -y
    - wget http://catfella.space/pkg/matrixgame_1_0-1_amd64.deb
    - dpkg -i matrixgame_1_0-1_amd64.deb
    - git clone https://github.com/linux-test-project/lcov
    - cd lcov/
    - make install
    - cd ..
    - gcc -Wall -Werror -c ${TEEN48GAME_PLAYERS_TESTS_PATH}${CI_COMMIT_REF_NAME}_tests.c -larrgame -lmatrixgame
    - gcc -Wall -Werror -fprofile-arcs -ftest-coverage -c ${TEEN48GAME_PLAYERS_PATH}${CI_COMMIT_REF_NAME}.c -larrgame -lmatrixgame
    - gcc -lgcov --coverage -o test.exe ${CI_COMMIT_REF_NAME}_tests.o ${CI_COMMIT_REF_NAME}.o -larrgame -lmatrixgame
    - ./test.exe
    - lcov -t "test" -o test.info -c -d .
    - genhtml -o ${TEEN48GAME_PLAYERS_TESTS_PATH}${CI_COMMIT_REF_NAME}_codecoverage test.info
  after_script:
    - rm -rf lcov/
    - rm *.o *.gcda *.gcno *.exe
  artifacts:
    name: codecoverage
    paths:
      - ${TEEN48GAME_PLAYERS_TESTS_PATH}${CI_COMMIT_REF_NAME}_codecoverage
    when: on_success
  only:
    refs:
      - /^teen48game_player_.*$/
