stages:
  - build
  - test

variables:
  MATRIX_FUNCS_PATH: MATRIXgame/functions/
  MATRIX_TESTS_PATH: MATRIXgame/tests/

build_matrixgame:
  stage: build
  image: gcc
  script:
    - gcc -Wall -Werror -c ${MATRIX_FUNCS_PATH}matrixgame_functions_*.c
  after_script:
    - rm *.o
  only:
    refs:
      - /^matrixgame_.*$/
    changes:
      - MATRIXgame/**/*.{c, h}
  except:
    refs:
      - matrixgame_transpose

build_matrixgame_openmp:
  stage: build
  image: gcc
  script:
    - gcc -Wall -Werror -c -fopenmp ${MATRIX_FUNCS_PATH}matrixgame_functions_*.c
  after_script:
    - rm *.o
  only:
    refs:
      - matrixgame_transpose
    changes:
      - MATRIXgame/**/*.{c, h}

test_matrixgame:
  stage: test
  image: gcc
  before_script:
    - rm -rf ${MATRIX_TESTS_PATH}${CI_COMMIT_REF_NAME}_codecoverage/
  script:
    - apt update -y
    - apt install libperlio-gzip-perl libjson-perl -y
    - git clone https://github.com/linux-test-project/lcov
    - cd lcov/
    - make install
    - cd ..
    - export CUR_FUNC=$(echo "$CI_COMMIT_REF_NAME" | sed 's/matrixgame_//')
    - gcc -Wall -Werror -c ${MATRIX_TESTS_PATH}*tests_${CUR_FUNC}.c
    - gcc -Wall -Werror -c ${MATRIX_FUNCS_PATH}matrixgame_functions_*.c
    - gcc -Wall -Werror -fprofile-arcs -ftest-coverage -c ${MATRIX_FUNCS_PATH}*functions_${CUR_FUNC}.c
    - gcc -lgcov --coverage -o test.exe matrixgame_tests_*.o matrixgame_functions_*.o
    - ./test.exe
    - lcov -t "test" -o test.info -c -d .
    - genhtml -o ${MATRIX_TESTS_PATH}${CI_COMMIT_REF_NAME}_codecoverage test.info
    - git config user.name "$GITLAB_USER_NAME"
    - git config user.email $GITLAB_USER_EMAIL
    - git add ${MATRIX_TESTS_PATH}${CI_COMMIT_REF_NAME}_codecoverage/
    - git commit -m "Add codecoverage directory for $CI_COMMIT_REF_NAME function"
    - git push https://${DEPLOY_USER}:${DEPLOY_TOKEN}@git.iu7.bmstu.ru/aolenev/iu7-cprog-sems-2019-aolenev.git HEAD:matrixgame_codecoverage
  after_script:
    - rm -rf lcov/
    - rm *.o *.gcda *.gcno *.exe
  only:
    refs:
      - /^matrixgame_.*$/
    changes:
      - MATRIXgame/**/*.{c, h}
  except:
    - matrixgame_transpose

test_matrixgame_openmp:
  stage: test
  image: gcc
  before_script:
    - rm -rf ${MATRIX_TESTS_PATH}${CI_COMMIT_REF_NAME}_codecoverage/
  script:
    - apt update -y
    - apt install libperlio-gzip-perl libjson-perl -y
    - git clone https://github.com/linux-test-project/lcov
    - cd lcov/
    - make install
    - cd ..
    - export CUR_FUNC=$(echo "$CI_COMMIT_REF_NAME" | sed 's/matrixgame_//')
    - gcc -Wall -Werror -fopenmp -c ${MATRIX_TESTS_PATH}*tests_${CUR_FUNC}.c
    - gcc -Wall -Werror -fopenmp -c ${MATRIX_FUNCS_PATH}matrixgame_functions_*.c
    - gcc -Wall -Werror -fprofile-arcs -ftest-coverage -fopenmp -c ${MATRIX_FUNCS_PATH}*functions_${CUR_FUNC}.c
    - gcc -lgcov --coverage -fopenmp -o test.exe matrixgame_tests_*.o matrixgame_functions_*.o
    - ./test.exe
    - lcov -t "test" -o test.info -c -d .
    - genhtml -o ${MATRIX_TESTS_PATH}${CI_COMMIT_REF_NAME}_codecoverage test.info
    - git config user.name "$GITLAB_USER_NAME"
    - git config user.email $GITLAB_USER_EMAIL
    - git add ${MATRIX_TESTS_PATH}${CI_COMMIT_REF_NAME}_codecoverage/
    - git commit -m "Add codecoverage directory for $CI_COMMIT_REF_NAME function"
    - git push https://${DEPLOY_USER}:${DEPLOY_TOKEN}@git.iu7.bmstu.ru/aolenev/iu7-cprog-sems-2019-aolenev.git HEAD:matrixgame_codecoverage
  after_script:
    - rm -rf lcov/
    - rm *.o *.gcda *.gcno *.exe
  only:
    refs:
      - matrixgame_transpose
    changes:
      - MATRIXgame/**/*.{c, h}
