stages:
  - build
  - test

variables:
  MATRIX_FUNCS_PATH: MATRIXgame/functions/
  MATRIX_TESTS_PATH: MATRIXgame/tests/

build_matrixgame:
  stage: build
  image: gcc
  script:
    - cd $MATRIX_FUNCS_PATH
    - gcc -Wall -Werror -c matrixgame_functions_*.c
  after_script:
    - cd $MATRIX_FUNCS_PATH
    - rm *.o
  only:
    - /^matrixgame_.*$/
  except:
    - matrixgame_transpose

build_matrixgame_openmp:
  stage: build
  image: gcc
  script:
    - cd $MATRIX_FUNCS_PATH
    - gcc -Wall -Werror -c -fopenmp matrixgame_functions_*.c
  after_script:
    - cd $MATRIX_FUNCS_PATH
    - rm *.o
  only:
    - matrixgame_transpose

test_matrixgame:
  stage: test
  image: gcc
  script:
    - cd $MATRIX_TESTS_PATH
    - gcc -Wall -Werror -c matrixgame_tests_*.c
    - cd ../../$MATRIX_FUNCS_PATH
    - gcc -Wall -Werror -c matrixgame_functions_*.c
    - gcc -o test ../../$MATRIX_TESTS_PATH/matrixgame_tests_*.o matrixgame_functions_*.o
    - ./test
  after_script:
    - cd $MATRIX_FUNCS_PATH
    - rm *.o
    - cd ../../$MATRIX_TESTS_PATH
    - rm *.o
  only:
    - /^matrixgame_.*$/
  except:
    - matrixgame_transpose

test_matrixgame_openmp:
  stage: test
  image: gcc
  script:
    - cd $MATRIX_TESTS_PATH
    - gcc -Wall -Werror -c -fopenmp matrixgame_tests_*.c
    - cd ../../$MATRIX_FUNCS_PATH
    - gcc -Wall -Werror -c -fopenmp matrixgame_functions_*.c
    - gcc -o test ../../$MATRIX_TESTS_PATH/matrixgame_tests_*.o matrixgame_functions_*.o
    - ./test
  after_script:
    - cd $MATRIX_FUNCS_PATH
    - rm *.o
    - cd ../../$MATRIX_TESTS_PATH
    - rm *.o
  only:
    - matrixgame_transpose