stages:
  - build
  - test

variables:
  MATRIX_FUNCS_PATH: MATRIXgame/functions/
  MATRIX_TESTS_PATH: MATRIXgame/tests/
  CODECOVERAGE: _codecoverage

build_matrixgame:
  stage: build
  image: gcc
  script:
    - cd $MATRIX_FUNCS_PATH
    - gcc -Wall -Werror -c matrixgame_functions_*.c
  after_script:
    - cd $MATRIX_FUNCS_PATH
    - rm *.o
  only:
    - /^matrixgame_.*$/
  except:
    - matrixgame_transpose

build_matrixgame_openmp:
  stage: build
  image: gcc
  script:
    - cd $MATRIX_FUNCS_PATH
    - gcc -Wall -Werror -c -fopenmp matrixgame_functions_*.c
  after_script:
    - cd $MATRIX_FUNCS_PATH
    - rm *.o
  only:
    - matrixgame_transpose

test_matrixgame:
  stage: test
  image: gcc
  script:
    - apt update -y
    - apt install lcov -y
    - cd $MATRIX_TESTS_PATH
    - gcc -Wall -Werror -fprofile-arcs -ftest-coverage -c matrixgame_tests_*.c
    - cd ../../$MATRIX_FUNCS_PATH
    - gcc -Wall -Werror -fprofile-arcs -ftest-coverage -c matrixgame_functions_*.c
    - gcc -lgcov --coverage -o test.exe ../../$MATRIX_TESTS_PATH/matrixgame_tests_*.o matrixgame_functions_*.o
    - ./test.exe
    - lcov -t "test" -o test.info -c -d .
    - genhtml -o ${CI_COMMIT_REF_NAME}_codecoverage test.info
    - git config user.name "$GITLAB_USER_NAME"
    - git config user.email $GITLAB_USER_EMAIL
    - git add ${CI_COMMIT_REF_NAME}_codecoverage/
    - git commit -m "Add codecoverage directory for $CI_COMMIT_REF_NAME function"
    - git push
  after_script:
    - cd $MATRIX_FUNCS_PATH
    - rm *.o *.gcda *.gcno *.exe
    - cd ../../$MATRIX_TESTS_PATH
    - rm *.o *.gcda *.gcno
  only:
    - /^matrixgame_.*$/
  except:
    - matrixgame_transpose

test_matrixgame_openmp:
  stage: test
  image: gcc
  script:
    - cd $MATRIX_TESTS_PATH
    - gcc -Wall -Werror -c -fopenmp matrixgame_tests_*.c
    - cd ../../$MATRIX_FUNCS_PATH
    - gcc -Wall -Werror -c -fopenmp matrixgame_functions_*.c
    - gcc -fopenmp -o test ../../$MATRIX_TESTS_PATH/matrixgame_tests_*.o matrixgame_functions_*.o
    - ./test
  after_script:
    - cd $MATRIX_FUNCS_PATH
    - rm *.o
    - cd ../../$MATRIX_TESTS_PATH
    - rm *.o
  only:
    - matrixgame_transpose
