stages:
  - build
  - test

variables:
  MATRIX_FUNCS_PATH: MATRIXgame/functions/
  MATRIX_TESTS_PATH: MATRIXgame/tests/

build_matrixgame:
  stage: build
  image: gcc
  script:
    - cd MATRIX_FUNCS_PATH
    - gcc -Wall -Werror -c matrixgame_functions_*.c
  only:
    - /^matrixgame_.*$/

test_matrixgame:
  stage: test
  image: gcc
  script:
    - cd MATRIX_TESTS_PATH
    - gcc -Wall -Werror -o test matrixgame_tests_*.c
    - ./test
  only:
    - /^matrixgame_.*$/
