# Получение объектных файлов
arrgame_functions_creat.o: ../functions/arrgame_functions_creat.c
	gcc -std=c99 -c -Wall -Werror -pedantic -o arrgame_functions_creat.o ../functions/arrgame_functions_creat.c
#Ваша_функция.o: Ваша_функция.c
#	gcc -std=c99 -c -Wall -Werror -pedantic -o Ваша_функция.o hello.c
# Итоговая компановка

#main: main.o func.o func.o func.o ...
#	gcc -std=c99 -Wall -Werror -pedantic -o hello main.o func.o func.o ...